### ISSUE TITLE
Possibility to add ssh public key from file during node create

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena-plugin-aws#40]
Currently it only prompts previously created keys from AWS.

**Comment by kke** [comment]
Doesn't seem to be possible in AWS API.

[Working with key pairs](http://docs.aws.amazon.com/sdk-for-ruby/v2/developer-guide/ec2-create-key-pair.html#aws-ruby-sdk-ec2-create-key-pair-code)
[CreateKeyPair API DOC](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateKeyPair.html)

Looks like it doesn't accept a key from input, you can only create new keys and get the generated private key (which seems a bit odd, why would you want the private key at all, instead of just getting the public one?).

**Comment by jakolehm** [comment]
Fixed in #41
